apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-auth
  template:
    metadata:
      labels:
        app: jwt-auth
    spec:
      containers:
        - name: jwt-auth
          image: registry.eta.com/jwt-auth:latest
          ports:
            - containerPort: 8012
---
apiVersion: v1
kind: Service
metadata:
  name: jwt-auth
spec:
  selector:
    app: jwt-auth
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
  type: LoadBalancer